### ISSUE TITLE
Can not save user setting of issue badge

### ISSUE THREAD

**Issue by vongola12324** [akiko-pusu/redmine_issue_badge#106]
Hi,

I just installed this plugin (version 0.1.1) on redmine 4.0.4. I can not save any setting that belongs to issue badge.
Here are the gif that recorded the action what I did.
![can not save setting](https://user-images.githubusercontent.com/5770715/65211811-9c31af80-dad2-11e9-8a44-cfa270180e57.gif)

Other setting in this page can be save correctly, also the settings in admin panel could be saved normally.

**Comment by akiko-pusu** [comment]
@vongola12324 Thanks for your reporting issue.
Please wait for a while to confirm the situation. Maybe this issue is related to #97 

Could you please give me some logs like this?

https://github.com/akiko-pusu/redmine_issue_badge/issues/97#issuecomment-526041327

**Comment by vongola12324** [comment]
Sure, here are the logs.
```
I, [2019-09-27T15:41:18.550047 #31283]  INFO -- : Started POST "/my/account" for [REMOVED] at 2019-09-27 15:41:18 +0800
I, [2019-09-27T15:41:18.551739 #31283]  INFO -- : Processing by MyController#account as HTML
I, [2019-09-27T15:41:18.551987 #31283]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"[REMOVED]", "user"=>{"firstname"=>"Admin", "lastname"=>"Redmine", "mail"=>"[REMOVED]", "language"=>"zh-TW", "mobile_phone"=>"", "mail_notification"=>"all", "notified_project_ids"=>[""]}, "commit"=>"儲存", "pref"=>{"no_self_notified"=>"0", "hide_mail"=>"0", "time_zone"=>"Taipei", "comments_sorting"=>"asc", "warn_on_leaving_unsaved"=>"1", "textarea_font"=>""}, "issue_badge"=>{"show_assigned_to_group"=>"1", "badge_order"=>"oldest"}}
I, [2019-09-27T15:41:18.561201 #31283]  INFO -- :   Current user: admin (id=1)
I, [2019-09-27T15:41:18.587841 #31283]  INFO -- : Redirected to https://[REMOVED]/my/account
I, [2019-09-27T15:41:18.588160 #31283]  INFO -- : Completed 302 Found in 36ms (ActiveRecord: 8.7ms)
I, [2019-09-27T15:41:18.600281 #31283]  INFO -- : Started GET "/my/account" for [REMOVED] at 2019-09-27 15:41:18 +0800
I, [2019-09-27T15:41:18.601235 #31283]  INFO -- : Processing by MyController#account as HTML
I, [2019-09-27T15:41:18.608779 #31283]  INFO -- :   Current user: admin (id=1)
I, [2019-09-27T15:41:18.612809 #31283]  INFO -- :   Rendering my/account.html.erb within layouts/base
I, [2019-09-27T15:41:18.616082 #31283]  INFO -- :   Rendered plugins/redmine_2fa/app/views/second_authentications/_reset.html.erb (0.4ms)
I, [2019-09-27T15:41:18.625644 #31283]  INFO -- :   Rendered plugins/redmine_2fa/app/views/redmine_2fa/hooks/_mobile_phone_form_field.html.erb (0.7ms)
I, [2019-09-27T15:41:18.634769 #31283]  INFO -- :   Rendered users/_mail_notifications.html.erb (8.5ms)
I, [2019-09-27T15:41:18.648616 #31283]  INFO -- :   Rendered users/_preferences.html.erb (13.5ms)
I, [2019-09-27T15:41:18.650061 #31283]  INFO -- :   Rendered plugins/redmine_issue_badge/app/views/my/_issue_badge_form.erb (1.1ms)
I, [2019-09-27T15:41:18.657419 #31283]  INFO -- :   Rendered my/_sidebar.html.erb (6.3ms)
I, [2019-09-27T15:41:18.657715 #31283]  INFO -- :   Rendered my/account.html.erb within layouts/base (44.7ms)
I, [2019-09-27T15:41:18.669480 #31283]  INFO -- : Completed 200 OK in 68ms (Views: 51.4ms | ActiveRecord: 9.2ms)
I, [2019-09-27T15:41:18.748593 #31283]  INFO -- : Started GET "/issue_badge" for [REMOVED] at 2019-09-27 15:41:18 +0800
I, [2019-09-27T15:41:18.749884 #31283]  INFO -- : Processing by IssueBadgeController#index as */*
I, [2019-09-27T15:41:18.757445 #31283]  INFO -- :   Current user: admin (id=1)
I, [2019-09-27T15:41:18.763996 #31283]  INFO -- :   Rendering plugins/redmine_issue_badge/app/views/issue_badge/_issue_badge.html.erb
I, [2019-09-27T15:41:18.764353 #31283]  INFO -- :   Rendered plugins/redmine_issue_badge/app/views/issue_badge/_issue_badge.html.erb (0.2ms)
I, [2019-09-27T15:41:18.764725 #31283]  INFO -- : Completed 200 OK in 15ms (Views: 1.0ms | ActiveRecord: 5.4ms)
```

I have changed some information, like IP,token, and email, into "[REMOVED]".

**Comment by AizeLeOuf** [comment]
same here with redmine 4.0.5 and current master

**Comment by akiko-pusu** [comment]
@vongola12324 @AizeLeOuf 
Sorry for my delayed reply.
Could you please let me know more detailed your environment?

Such as DB, Plugin you use, Application Server (Unicorn? Passenger?) and Web server.

If my_controller_patch works fine and accepts the request, passed parameters should be logged as following:

https://github.com/akiko-pusu/redmine_issue_badge/blob/20941a7142f0f0262b29da1dbf2a9583d3fbaffa/lib/issue_badge/my_controller_patch.rb#L14-L15

**Comment by AizeLeOuf** [comment]
The fix was provided in https://github.com/akiko-pusu/redmine_issue_badge/issues/97#issuecomment-525967261

> Change from
> 
> if request.put?
> 
> To
> 
> if request.put? || request.post?
> 
>

**Comment by akiko-pusu** [comment]
@AizeLeOuf 
Thanks for the above comment! I'll do an additional workaround!

**Comment by akiko-pusu** [comment]
I've just added the workaround and released v0.1.2.
Please confirm and give feedback!

**Comment by AizeLeOuf** [comment]
> I've just added the workaround and released v0.1.2.
> Please confirm and give feedback!

Works like a charm ! Nice feature in 0.1.2 let's try it
FYI, it's me ecedi-ld, I pushed french translation with another account but it's me ;)

**Comment by akiko-pusu** [comment]
@AizeLeOuf Ok, I'll apply your PR! Thanks again!

**Comment by vongola12324** [comment]
@akiko-pusu Sorry for replying so late, there was too much work last week. 😢 
It looks like the function is working properly. Hurray!! 🎉 

BTW, It seems you have tagged wrong id on release message. 
My id is vongola12324, not Vongola. 🤣
