### ISSUE TITLE
Custom Query

### ISSUE THREAD

**Issue by koren85** [akiko-pusu/redmine_issue_badge#107]
Hello!
It would be great to be able to use a custom query instead of a predefined one. What do you think?

**Comment by akiko-pusu** [comment]
@koren85 Thanks for trying and using my plugin!

> It would be great to be able to use a custom query

It's interesting. Could you please give me more information about your hope?
For example, the current version of this plugin, displayed budge number is the number of issues that the user is assigned.
If we use the custom query, what is the number to be displayed?

**Comment by koren85** [comment]
Yes of course.
Consider an example where the user should not pay attention to all the tasks that are assigned to him, but selected by a specific filter. For example, all tasks assigned to me in the "New" status, with an update date of at least one day.
By configuring the plug-in with custom filters, we can widely adapt it to work processes in my organization. It was great to see this soon.

**Comment by bviktor** [comment]
We're having **constant** issues with users not realizing an issue is awaiting their feedback, so issues are often left untouched for weeks, until they finally ping each other via IM or email or something.

For this very reason, pretty much the whole company started messing around with the assignee field instead - when they want someone's input, they set them as the assignee, so that they don't forget to reply. Which is extremely stupid. Yes, I know, there's email notifications, I just can't make people actually read them. Don't ask me why it's so darn difficult...

To put an end to this madness, I think it'd be awesome to have a second, say, blue badge like "Issues awaiting my feedback", which is essentially the issues where

- Status: feedback
- Author: &lt;me&gt;

What do you think? Should I open a separate request, or do you think it's out of the realm of this plugin? I've been flirting with the idea of trying to extend the plugin on my own, but it'll prolly take 10 times more time to achieve coz I suck hard at Ruby lol.

**Comment by bviktor** [comment]
Actually, it's almost the same thing as what @koren85 is asking for. With one difference, I'd really prefer a _secondary_ badge instead of replacing the current one.

There could be admin plugin settings to
- enable the second badge
- define the query for the second badge

**Comment by koren85** [comment]
we also use the unread issue plugin. Perhaps you will also be useful. and with the custom menu plugin it becomes more convenient to view a list of problems

**Comment by bviktor** [comment]
Unfortunately that uses some Ruby encoder stuff that's not even compatible with Ruby 2.6 which we're using... I just don't get it why they're so afraid to release their code to the public if it's a free plugin anyway. Also makes me question if I really want to use it, there's some red flags here:

- encrypted source code
- site has incorrectly set up SSL
- uses some "a_common_libs" stuff, which is, again, encrypted

**Comment by akiko-pusu** [comment]
Hi, @koren85 , @bviktor Thanks for your feedback!

> so issues are often left untouched for weeks, until they finally ping each other via IM or email or something.

Recently I started to use Redmine again, and now I understand this situation and request. 

Exp.
- Operators want to know how many issues which are not assigned and must be assigned.
- Issue reporter want to know that there is a issue to reply or not.
and so on.

Personally I feel a little messy if the second badge is also displayed.
So I think users can switch the condition to show the number of issues at my page.
Default is assigned to me, but users can choose other condition based on custom query.

**Comment by koren85** [comment]
Returning to  @bviktor message about team interaction. I would like to add that it is very difficult to get feedback from a participant who, for whatever reason, does not view tasks in which he is expected to receive an answer. I am more inclined to the option of forcibly viewing the list of tasks for such participants. Perhaps as a popup on top of all Redmine windows. And exit from the mode by checkbox (viewed / answered) ... Otherwise, the project manager spends too much time and effort to get a response from the participant.

**Comment by bviktor** [comment]
Currently we "solve" that by assigning the ticket to the one we want feedback from, and once they respond, they assign the ticket back. But it's and extremely stupid and upside down way of solving the problem. I fought against it, but after all, it's been pushed down from the COO level lol...

**Comment by akiko-pusu** [comment]
Hi, @koren85  and @bviktor.

I've just implemented the custom query feature and now merged into develop branch.
(Please see: #115)
I hope this feature meets your request.

**Comment by bviktor** [comment]
Thank you, I'll test it out asap!

**Comment by koren85** [comment]
thanks in advance! I'll start using it on my team!

**Comment by akiko-pusu** [comment]
@koren85 @bviktor 
Sorry, This update is now only applied to the develop branch.
I'm going to release the next version, 0.1.2,  including this feature as soon as possible.

**Comment by akiko-pusu** [comment]
Merged and released v0.1.2.
