### ISSUE TITLE
Badge color is wrong on mobile

### ISSUE THREAD

**Issue by rafaelmartinsrm** [akiko-pusu/redmine_issue_badge#108]
The badge background-color is green when on mobile view and red on desktop view.

As a suggestion I think it should have a preference for green when = 0 and red when > 0.

**Comment by akiko-pusu** [comment]
@rafaelmartinsrm Thanks for your nice suggestion!
I'm going to take your opinion into account:smile:

**Comment by akiko-pusu** [comment]
Both mobile and desktop:
 - when no assigned issue / count 0: color = green
 - when has assigned issues / count gt or = to 1: color = red

**Comment by rafaelmartinsrm** [comment]
It's a good improvement.

**Comment by akiko-pusu** [comment]
Hi, @rafaelmartinsrm 
I've just merged into the master branch. Thanks for your feedback!
