### ISSUE TITLE
Wrong version number?

### ISSUE THREAD

**Issue by vsc55** [akiko-pusu/redmine_issue_badge#109]
Hello,
Both on the web "https://www.redmine.org/plugins/redmine_issue_badge", and when checking for updates in the extensions section, it says that the latest version is 0.1.2. But in github when downloading the repository, 0.1.1 appears in both the master and developer branches.
Best regards.

**Comment by akiko-pusu** [comment]
Hi, @vsc55 
Thanks for your pointing out!
I've just fixed it to the right version at the Redmine plugins directory.
Highly appreciated!
