### ISSUE TITLE
Redmine not at root

### ISSUE THREAD

**Issue by rogerjak** [akiko-pusu/redmine_issue_badge#13]
Great plugin, but when you don't have Redmine installed at root, some of the links are wrong.

**Comment by akiko-pusu** [comment]
Hi, @rogerjak .
Thank you so much for your bug report.
I'll confirm and fix this as soon as possible!

**Comment by akiko-pusu** [comment]
Hi, @rogerjak 
I found the dead link to all my issues filter, and fixed it.
Now, plugin is version 0.0.2 and could you please try the latest version.
