### ISSUE TITLE
how to upgrade

### ISSUE THREAD

**Issue by yousefchtourou** [akiko-pusu/redmine_issue_badge#131]
how to upgrade from 0.0.6 to 0.1.3

**Comment by akiko-pusu** [comment]
@yousefchtourou 
Hi, thanks for using my plugin!
Do you use Redmine 4.x? 
You can update by following this step.
https://github.com/akiko-pusu/redmine_issue_badge#plugin-installation

- git clone or download plugin's source code from here:
  - https://github.com/akiko-pusu/redmine_issue_badge/releases/tag/0.1.3
- Store plugin's source code under your Redmine's plugins/ directory.

Then, run the migration command.

```bash
rails redmine:plugins:migrate RAILS_ENV=production
```
