### ISSUE TITLE
issue_badge

### ISSUE THREAD

**Issue by nachoan** [akiko-pusu/redmine_issue_badge#18]
Hi, 

Thanks for the plugin. 

We have some problem on screen with the box containing issues. Is it easy to fix?

I think the problem with the label 
div id="issue_badge"

![seleccion_384](https://cloud.githubusercontent.com/assets/8542490/14700899/91bc7578-07a2-11e6-804f-c13602d31de8.png)

**Comment by akiko-pusu** [comment]
@nachoan , thank you for reporting issue.
I hope to fix this problem,  so that could you please tell me your Redmine's theme if you use non builtin theme.

**Comment by nachoan** [comment]
We are using Abacus Theme http://www.abacusthemes.com/en/
Do you think I must send a message to the author?

**Comment by akiko-pusu** [comment]
@nachoan , thanks for your additional information.
> Do you think I must send a message to the author?
I don’t think so. First, I’ll try to apply above theme.
