### ISSUE TITLE
migrate error

### ISSUE THREAD

**Issue by juxta73** [akiko-pusu/redmine_issue_badge#28]
Hello!

I have problem with migrate. Error log

root@66300:/var/www/redmine# rake redmine:plugins:migrate NAME=redmine_issue_badge RAILS_ENV=production
/usr/local/rvm/gems/ruby-2.3.3/gems/htmlentities-4.3.1/lib/htmlentities/mappings/expanded.rb:465: warning: key "inodot" is duplicated and overwritten on line 466
rake aborted!
NoMethodError: undefined method `safe_attributes' for #<Class:0x000000043e47f8>
Did you mean?  cache_attributes
               scope_attributes
               cached_attributes
               scope_attributes?
               cache_attribute?
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.2.7.1/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
/var/www/redmine/plugins/redmine_issue_badge/lib/issue_badge/user_preference_patch.rb:9:in `block in included'
/var/www/redmine/plugins/redmine_issue_badge/lib/issue_badge/user_preference_patch.rb:4:in `class_eval'
/var/www/redmine/plugins/redmine_issue_badge/lib/issue_badge/user_preference_patch.rb:4:in `included'
/var/www/redmine/plugins/redmine_issue_badge/init.rb:11:in `include'
/var/www/redmine/plugins/redmine_issue_badge/init.rb:11:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:446:in `instance_exec'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:446:in `block in make_lambda'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:192:in `block in simple'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `block in call'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `each'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `call'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_prepare_callbacks'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
/usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.2.7.1/lib/rails/application/finisher.rb:50:in `block in <module:Finisher>'
/usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
/usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
/var/www/redmine/config/environment.rb:14:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.3/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.3.3/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/var/www/redmine/plugins/periodictask/lib/tasks/periodictask.rake:7:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
/var/www/redmine/lib/tasks/redmine.rake:186:in `block in <top (required)>'
/var/www/redmine/lib/tasks/redmine.rake:186:in `each'
/var/www/redmine/lib/tasks/redmine.rake:186:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
/usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.2.7.1/lib/rails/engine.rb:658:in `block in run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.2.7.1/lib/rails/engine.rb:658:in `each'
/usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.2.7.1/lib/rails/engine.rb:658:in `run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.2.7.1/lib/rails/application.rb:452:in `run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.2.7.1/lib/rails/engine.rb:453:in `load_tasks'
/usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `public_send'
/usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `method_missing'
/var/www/redmine/Rakefile:7:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.3/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
root@66300:/var/www/redmine# >   21:24:40 Socket error: Undefined error: 0

------------
Environment:
  Redmine version                3.3.1.stable.16111
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.9.3
  Git                            2.7.4
  Filesystem                     
Redmine plugins:
  periodictask                   3.1.1
  redmine__select2               1.1.0
  redmine_banner                 0.1.2
  redmine_checklists             3.1.5
  redmine_ckeditor               1.1.4
  redmine_customize              1.2.3
  redmine_lightbox2              0.3.1
  sidebar_hide                   0.0.8
-------------

**Comment by akiko-pusu** [comment]
@juxta73 
Thank you so much for your reporting issue and I’m sorry to trouble you.
Which version  is your redmine issue badge, 0.0.3 or 0.0.4?
Because I’ve just updated this plugin to 0.0.4 yesterday.

**Comment by akiko-pusu** [comment]
@juxta73, I’ve just found the reason for this problem, so please wait for a while till fix it.
If you could apply quick workaround, please comment out redmine_issue_badge/lib/issue_badge/user_preference_patch.rb:4, safe_attributes :issue_badge line.

```
  module UserPreferencePatch
    def self.included(base)
      base.class_eval do
        unloadable # Send unloadable so it will not be unloaded in development
        after_destroy :destroy_issue_badge

        has_one :issue_badge_user_setting, dependent: :destroy
        #safe_attributes :issue_badge # here!
      end
    end
```

**Comment by akiko-pusu** [comment]
Sorry, I’ve just fixed it. Please try v0.0.4.1.

**Comment by juxta73** [comment]
now works great with migrate! thank you so much, @akiko-pusu
