### ISSUE TITLE
suggestion of applying to all users

### ISSUE THREAD

**Issue by marilawang** [akiko-pusu/redmine_issue_badge#3]
Hi,
I've tried this awesome plugin, thanks!

But I really need that all users to turn on this feature, not manually set by each user their own.

**Comment by akiko-pusu** [comment]
Thank you so much for your request.
The reason why this plugin is enabled by each user own is that I hope to prevent performance reducing.
If the site has many active users,  their settings will have any performance effect on the server.

But, there's reason in what you point out :)
Please wait for a while.
My plan is following:

- Default, admin can switch the option to use this or not.
 - If turn on, badge will be shown all the users (who can handle issues) .

- Each user can overwrite above global setting. 
 - If she/he wan't to show badge, can turn off at user preference.

**Comment by acki** [comment]
That would be nice!

**Comment by archonwang** [comment]
+1

**Comment by Enkil** [comment]
+1

**Comment by akiko-pusu** [comment]
Hi, @marilawang 
Thank you for your request. I’ve add this feature in ver 0.0.3.
If you have time, please try and give feedback.
