### ISSUE TITLE
Disable uppercase text in issue list + special characters

### ISSUE THREAD

**Issue by pousterlus** [akiko-pusu/redmine_issue_badge#32]
Hello !

Great work, I love this plugin.
But just 2 details I would love to change but can't find anywhere to change it : 
- In issue list, text is forced uppercase : how to change that ?
- In issue list, special characters seems to be shown with their HTML code, for example : "111 Add a new fied named & quot;adminaccess& quot;" : is it possible to have the " sign not being replaced by "& quot;" ?

Thanks,

-- 
Léo.

**Comment by pousterlus** [comment]
Hi again,

Sorry, the uppercase was part of another CSS file, I fixed it.
I'm still stuck with the special characters detail...

-- 
Léo.

**Comment by akiko-pusu** [comment]
Thanks for your feedback and issue report!
I’ll fix it as soon. And feel free to send me your suggestions!

**Comment by pousterlus** [comment]
You're welcome :)
You did a great job with this plugin, everyone in my company loves it !

Thanks for acknowledging the issue, please note that's not urgent !
I have some suggestions to improve it, I'll open new issues on github soon :)

Regards,

-- 
Léo.

**Comment by akiko-pusu** [comment]
I’ve merged workaround into master. If you have time, please confirm issue is fixed.
Also I’m going to ready to release bug fixed version, soon.

**Comment by pousterlus** [comment]
Hi there !
Thank you for giving some of your time to the community :)
I confirm your patch is working as expected.

ありがとう ございます

:)

Regards,

-- 
Léo.
