### ISSUE TITLE
Cannot change user password when "Display badge for all users" is ON

### ISSUE THREAD

**Issue by nakat-t** [akiko-pusu/redmine_issue_badge#36]
Procedure:
1. Turn on "Display badge for all users"
2. Create new user as "Must change password at next logon"
3. Login as new user => redirect to change password screen
4. Screen elements are duplicated and increased every 1 second.

Perhaps, It is a problem that load_badge('/issue_badge') was called but redirected to '/my/password'.

```
Environment:
  Redmine version                3.3.2.stable
  Ruby version                   2.2.6-p396 (2016-11-15) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
Redmine plugins:
  redmine_issue_badge            0.0.4.1
```

**Comment by akiko-pusu** [comment]
Hi, @nakat-t 
Thank you so much for your reporting this problem, any information is highly appreciated.
I’m going to review and fix soon.

**Comment by akiko-pusu** [comment]
@nakat-t 
I could reproduce above situation, and thank you so much your information again.
As you supposed, this is because ajax request to issue badge controller is blocked and redirected in case user is required password change, due to application controller.

Here is a quick workaround:

1. Prevent to render contend in case ajax request is redirected and not include issue badge template.
 
```
--- a/assets/javascripts/issue_badge.js
+++ b/assets/javascripts/issue_badge.js
@@ -5,7 +5,9 @@ function load_badge(url) {
         async: true,
         type: 'get'
     }).done(function( html ) {
-        $('#loggedas').after(html);
+        if ($(html).filter('div#issue_badge').length) {
+            $('#loggedas').after(html);
+        }
     });
 }
```

2. Prevent to load javascript in case user is required password change.

```
--- a/lib/issue_badge/application_hooks.rb
+++ b/lib/issue_badge/application_hooks.rb
@@ -6,7 +6,7 @@ module IssueBadge
       base_url = Redmine::Utils.relative_url_root
       badge_url = base_url + '/issue_badge'
       o = ''
-      if User.current.logged?
+      if User.current.logged? && User.current.change_password_allowed
         global_enabled = Setting.plugin_redmine_issue_badge['activate_for_all_users'] == 'true'
         o = stylesheet_link_tag('style', plugin: 'redmine_issue_badge')
         if User.current.pref.issue_badge || global_enabled
```

Anyway, I’m going to fix this as soon as possible.

**Comment by akiko-pusu** [comment]
I’ve applied bug fix into master branch. Thank you so much!

**Comment by nakat-t** [comment]
I verified that it was fixed in master. Thank you very much for your work.
