### ISSUE TITLE
Improvement : Issues from the group and not only mines

### ISSUE THREAD

**Issue by pousterlus** [akiko-pusu/redmine_issue_badge#41]
Hi there :)

As promised, I've got another feedback for improving your plugin efficiency.
As now, the plugin's working great, and I see my issues.
But I'm also a member of a group : Could it be possible to have an option to also show in the same list the issues assigned to the group ?

Would be great !

-- 
Léo.

**Comment by akiko-pusu** [comment]
Hi, thanks for this request.
Now issue badge return the number of issues which assigned to user and his/her group.

https://github.com/akiko-pusu/redmine_issue_badge/blob/master/app/controllers/issue_badge_controller.rb#L10

> all_issues = Issue.visible.open.where(assigned_to_id: ([User.current.id] + User.current.group_ids))

If number of assigned issues are less than 6, the issue assigned to group will be shown, but if have more than 6, 
Do you hope issues should be listed separately?
E.g.  List of oldest top 5 issues assigned to user, and List of oldest top 5 issues assigned to group.

**Comment by pousterlus** [comment]
Hi Akiko,

Wow, that was quick. You're fast ! :)
It's night in Paris right now, so I can't test it immediately, but you asked a really important question : with my request, "group issues" can hide "individual issues".

You probably have the best idea : Show group issues only if there is not much individual issues.

I think, if it's possible, you have to give the user the opportunity to trigger the group issue display, maybe in the "my account" preferences, maybe by adding a new box "Show group issues in the list" or something, next to the actual box "Show badge".
With that option, every user can have the choice ?

What do you think ?

Regards,

-- 
Léo, Paris - France.

**Comment by akiko-pusu** [comment]
Hi, I’ve just released v0.0.5, including this feature.
You can see additional option "Include issue numbers assigned to group” on user preference. 
Also, add css to classify issue assigned to user or assigned to group, like this:

![issue_list](https://cloud.githubusercontent.com/assets/122621/23865735/fa7301a0-0859-11e7-9f07-9d18e09c1a96.png)


This release is even as a prototype, so please send feedback if you have!
