### ISSUE TITLE
Badge is not working for user created from LDAP user.

### ISSUE THREAD

**Issue by akiko-pusu** [akiko-pusu/redmine_issue_badge#49]
Reported: http://www.redmine.org/boards/3/topics/52408?r=52456#message-52456
This is because User#change_password_allowed? method return false in case auth_source_id.present?

**Comment by yusami** [comment]
Akiko-san,

Thank you for releasing the great plugin.
This change b7cc882 enables my Redmine to show the badge finally,
which is installed by Bitnami. I am waiting for the next release with this fix.

**Comment by akiko-pusu** [comment]
@yusami Thanks for your interest in my plugins. Commit b7cc882 is already merged into master.
And I’ve just released v0.0.6, including this bug fix.

This release, v0.0.6 is intended to this fix bugs, so that there is no big additional feature.
Only additional feature is https://github.com/akiko-pusu/redmine_issue_badge/pull/52. 
I wonder if this feature will be accepted or not by everyone. 
Feel free to give feedback!

ご利用くださってありがとうございます！
日本語でのリクエストやご意見でも全くかまいません。修正版としてv0.0.6を出しておりますので、よろしかったら使ってみてください。

ただ、 #52 で担当チケットが無しの時に画像と新規チケット作成のリンクを表示するようにしてみました。
みなさんに受け入れてもらえる調整かどうか自分でも不安なので、こちらの件も含めてご意見があれば、ぜひよろしくお願いいたします。

**Comment by yusami** [comment]
@akiko-pusu Thank you for releasing v0.0.6. It works fine for me. #52 is also good by showing the cool icon.
