### ISSUE TITLE
JS bug

### ISSUE THREAD

**Issue by marilawang** [akiko-pusu/redmine_issue_badge#5]
this line:
```
 if (!$.contains($("#issue_badge_contents")[0], event.target)) {
```
somehow cause an error in jQuery,

it should be write like this:

```
if (!$(event.target).is("#issue_badge_contents")) {
...
}
```

**Comment by akiko-pusu** [comment]
Hi, @marilawang 
Thank you for your reporting this issue and trying to use my small plugin!

I've just confirmed this error like this:
![issue5-js-error](https://cloud.githubusercontent.com/assets/122621/11159976/f9042564-8aa7-11e5-9446-661c36b53dc7.jpg)

And I'm going to apply your code soon. Thanks again!

**Comment by akiko-pusu** [comment]
@marilawang , I also merged above into master branch.
Thank you so much for your support!
