### ISSUE TITLE
UI error

### ISSUE THREAD

**Issue by kay54068** [akiko-pusu/redmine_issue_badge#56]
UI overlapping:

![image](https://cloud.githubusercontent.com/assets/3054544/25663657/d8ff2936-304a-11e7-83d8-bda47310474c.png)

**Comment by akiko-pusu** [comment]
Hi, @kay54068
Thanks for using this plugin.
Could you please tell me the version of this badge plugin and theme that you use?

**Comment by kay54068** [comment]
I use the 0.0.6 have UI overlapping but 0.0.5 is not.

information:

Environment:
  Redmine version                3.3.2.stable.16379
  Ruby version                   2.2.6-p396 (2016-11-15) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.9.3
  Git                            2.11.0
  Filesystem

**Comment by akiko-pusu** [comment]
Thanks.  And what theme do you use?

**Comment by akiko-pusu** [comment]
@kay54068 

CSS was changed from v0.0.5 to v0.0.6, and you can review what parts changed at this PR:
https://github.com/akiko-pusu/redmine_issue_badge/pull/52

I personally think your problem will be solved with **clearing your cache** , including css.

Could you please check if these lines are included or not at  http://YOUR_REDMINE_DOMAIN/plugin_assets/redmine_issue_badge/stylesheets/style.css,  with using your browser developer tool.

Added lines are here:
https://github.com/akiko-pusu/redmine_issue_badge/blob/master/assets/stylesheets/style.css#L104..L120

------

And, this is jus a FYI.

It seems you use Redmine v3.3.2, and this version still has following problem related JS/CSS cache.
* http://www.redmine.org/issues/24617
(This will be fixed next release, v3.3.4.)
