### ISSUE TITLE
Configurable issue number

### ISSUE THREAD

**Issue by bviktor** [akiko-pusu/redmine_issue_badge#63]
What do you guys think about making the number of issues displayed from the badge configurable as a user setting? 5 seems a pretty low number for 1080p+ displays.

**Comment by akiko-pusu** [comment]
I personally think 5 issues are enough at popup. Because if user has assigned issues more than 5 and user hopes to show all the issues, user can display his "my page” or “assigned issues” screen.
(Like Facebook Notification)

**Comment by akiko-pusu** [comment]
Related: #67

**Comment by akiko-pusu** [comment]
v0.1.2 includes this feature. (Range: 5, 10, 15, 20)

**Comment by bviktor** [comment]
Thanks a lot!
