### ISSUE TITLE
is it possible to custom the badge?

### ISSUE THREAD

**Issue by Jiangshan00001** [akiko-pusu/redmine_issue_badge#67]
This plugin is great and i love it.
I just want to know that if it is possible to custom the badge.
1. the badge display some issue, according to a custom query, instead of the fixed query. and the comment that what it is is set by user.
2. the badge number could be set by administrator.

then i could add a badge with assigned issue, or created issue, or watched issue, or 1-month updated issue and so on.
but i have no ruby rails skill...
thanks.

**Comment by Jiangshan00001** [comment]
alternatively, could i add some more badge: 
1 issues that i created and in finish status 
2 issues that i watched and not in close status
any suggestion that how to change the code manually is helpful.
thanks.

**Comment by akiko-pusu** [comment]
👀

**Comment by Jiangshan00001** [comment]
I have add a patch for add some more badge.
maybe someone need it.

**Comment by akiko-pusu** [comment]
related: #107

**Comment by akiko-pusu** [comment]
I've just implemented this feature and now merged into develop branch.
Soon I'm going to release new version.

**Comment by bviktor** [comment]
Awesome, thank you!
