### ISSUE TITLE
Show issues in project was closed long time ago

### ISSUE THREAD

**Issue by annguyenthienit** [akiko-pusu/redmine_issue_badge#81]
Dear Author,

- Currently, your plugin show issues were closed a long time ago. Can you fix it? Thank you so much!

**Comment by akiko-pusu** [comment]
Hi, @annguyenthienit, thanks for reporting issue.
But I'm sorry I can't figure out this clearly. Could you explain it in more detail?

**Comment by annguyenthienit** [comment]
Thanks for your quick reply.
For example as below:
Project1 was closed (Status is closed). Some tickets on it assigns to me.
Project2 is opening (Status is open). Some tickets on it assigns to me.

When I added your plugin. I saw list ticket from Project1 and Project2. But, I only want to see ticket on Project2.

**Comment by akiko-pusu** [comment]
Ok, I understood.  I’m going to confirm this situation and to make some workaround.
Thanks for your feedback.

**Comment by annguyenthienit** [comment]
:) Thank you so much! If I archive this project. We will not see this project on the notification list.
Besides, I think you need to create more option how many tickets will show. Currently, we only see 5 tickets.

**Comment by akiko-pusu** [comment]
Hi,  I applied this feature on v0.7.0.
Now exclude archived project's issues :)

Rref. https://github.com/akiko-pusu/redmine_issue_badge/commit/f8470cc4bc8db6bffcea23b1b0d9c81a37a7b24c#diff-c2a2bcb6ebf56c7cbbcce8d2d85e9eb2R38
