### ISSUE TITLE
Reverse order when clicking badge

### ISSUE THREAD

**Issue by pielat** [akiko-pusu/redmine_issue_badge#82]
Hello,
Currently when I click on badge I see 5 very old tasks in my Redmine. I think it will be more useful when I would see 5 newest tasks. It would be more like Facebook notifications :)
Do you think it's good idea to implement this?

**Comment by nguyenquangvinh** [comment]
Yes, it is. I already made some small modified at line 37 of file app/controllers/issue_badge_controller.rb. Changed to this:
Issue.visible.open.where(assigned_to_id: condition).order(updated_on: :desc)

So, the list now shows in order of newest issues first. Hope it help

**Comment by akiko-pusu** [comment]
@pielat @nguyenquangvinh 
Thanks for using my plugin and feedback. It's acceptable so try to implement this :)

**Comment by akiko-pusu** [comment]
@pielat @nguyenquangvinh 
Thanks for your feedback.
I've just released v0.0.7 included this feature.
If you still use Redmine 3.x, please try v0.0.7.
If you already migrated Redmine to Redmine4.x, v0.0.7 will be failed at the lugin migration task.
I'm going to release next version to support Redmine4.x soon.
